### ISSUE TITLE
What's the IB API version SwiftIB is based on? 

### ISSUE THREAD

**Issue by joe528** [kcome/SwiftIB#1]
@kcome 

I was looking for a way to glue IB's Posix API with Swift. After searching a lot, I just found SwiftIB, I can't believe someone actually ported the whole client into Swift directly. What a great job!

I am wondering which IB API version it is based on? What's your plan for future releases?

Since IB keeps pushing out new versions for its API, any concern if SwiftIB stays as it is now? How to keep up with new versions?

**Comment by kcome** [comment]
IB API basic interface doesn't change a between versions I believe.
